name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
      - run: npm ci
      - run: npm run build:server
      - run: npm run build:client
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'bangmoa'
          heroku_email: 'somn45@gmail.com'
          procfile: 'worker: node dist/index.js'
